// Mocks generated by Mockito 5.4.6 from annotations
// in oqueeoquee/test/features/jokes/presentation/providers/joke_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:oqueeoquee/core/error/failures.dart' as _i6;
import 'package:oqueeoquee/core/usecases/usecase.dart' as _i8;
import 'package:oqueeoquee/features/jokes/domain/entities/joke.dart' as _i7;
import 'package:oqueeoquee/features/jokes/domain/repositories/joke_repository.dart'
    as _i2;
import 'package:oqueeoquee/features/jokes/domain/usecases/dislike_joke.dart'
    as _i12;
import 'package:oqueeoquee/features/jokes/domain/usecases/get_next_joke.dart'
    as _i4;
import 'package:oqueeoquee/features/jokes/domain/usecases/increment_view_count.dart'
    as _i9;
import 'package:oqueeoquee/features/jokes/domain/usecases/like_joke.dart'
    as _i11;
import 'package:oqueeoquee/features/jokes/domain/usecases/reset_view_counters.dart'
    as _i10;
import 'package:oqueeoquee/features/jokes/domain/usecases/sync_with_remote.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeJokeRepository_0 extends _i1.SmartFake
    implements _i2.JokeRepository {
  _FakeJokeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetNextJoke].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNextJoke extends _i1.Mock implements _i4.GetNextJoke {
  MockGetNextJoke() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JokeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJokeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JokeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Joke>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Joke>>.value(
            _FakeEither_1<_i6.Failure, _i7.Joke>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Joke>>);
}

/// A class which mocks [IncrementViewCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementViewCount extends _i1.Mock
    implements _i9.IncrementViewCount {
  MockIncrementViewCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JokeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJokeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JokeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i9.IncrementViewCountParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [ResetViewCounters].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetViewCounters extends _i1.Mock implements _i10.ResetViewCounters {
  MockResetViewCounters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JokeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJokeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JokeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [LikeJoke].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikeJoke extends _i1.Mock implements _i11.LikeJoke {
  MockLikeJoke() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JokeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJokeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JokeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i11.LikeJokeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DislikeJoke].
///
/// See the documentation for Mockito's code generation for more information.
class MockDislikeJoke extends _i1.Mock implements _i12.DislikeJoke {
  MockDislikeJoke() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JokeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJokeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JokeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i12.DislikeJokeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [SyncWithRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncWithRemote extends _i1.Mock implements _i13.SyncWithRemote {
  MockSyncWithRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JokeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeJokeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.JokeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
