// Mocks generated by Mockito 5.4.6 from annotations
// in oqueeoquee/test/features/jokes/domain/usecases/get_next_joke_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:oqueeoquee/core/error/failures.dart' as _i5;
import 'package:oqueeoquee/features/jokes/domain/entities/joke.dart' as _i6;
import 'package:oqueeoquee/features/jokes/domain/repositories/joke_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JokeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJokeRepository extends _i1.Mock implements _i3.JokeRepository {
  MockJokeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Joke>>> getJokes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getJokes,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Joke>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Joke>>(
          this,
          Invocation.method(
            #getJokes,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Joke>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>> getNextJoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextJoke,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>>.value(
            _FakeEither_0<_i5.Failure, _i6.Joke>(
          this,
          Invocation.method(
            #getNextJoke,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> incrementViewCount(int? jokeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementViewCount,
          [jokeId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #incrementViewCount,
            [jokeId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetViewCounters() =>
      (super.noSuchMethod(
        Invocation.method(
          #resetViewCounters,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetViewCounters,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>> createJoke({
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJoke,
          [],
          {
            #question: question,
            #answer: answer,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>>.value(
            _FakeEither_0<_i5.Failure, _i6.Joke>(
          this,
          Invocation.method(
            #createJoke,
            [],
            {
              #question: question,
              #answer: answer,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>> updateJoke({
    required int? id,
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJoke,
          [],
          {
            #id: id,
            #question: question,
            #answer: answer,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>>.value(
            _FakeEither_0<_i5.Failure, _i6.Joke>(
          this,
          Invocation.method(
            #updateJoke,
            [],
            {
              #id: id,
              #question: question,
              #answer: answer,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Joke>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteJoke(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteJoke,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteJoke,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> likeJoke(int? jokeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #likeJoke,
          [jokeId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #likeJoke,
            [jokeId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> dislikeJoke(int? jokeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #dislikeJoke,
          [jokeId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #dislikeJoke,
            [jokeId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> syncWithRemote() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #syncWithRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
