// Mocks generated by Mockito 5.4.6 from annotations
// in oqueeoquee/test/features/jokes/data/repositories/joke_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oqueeoquee/features/jokes/data/datasources/joke_local_datasource.dart'
    as _i3;
import 'package:oqueeoquee/features/jokes/data/datasources/joke_remote_datasource.dart'
    as _i5;
import 'package:oqueeoquee/features/jokes/data/models/joke_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeJokeModel_0 extends _i1.SmartFake implements _i2.JokeModel {
  _FakeJokeModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JokeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJokeLocalDataSource extends _i1.Mock
    implements _i3.JokeLocalDataSource {
  MockJokeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.JokeModel>> getJokes() => (super.noSuchMethod(
        Invocation.method(
          #getJokes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.JokeModel>>.value(<_i2.JokeModel>[]),
      ) as _i4.Future<List<_i2.JokeModel>>);

  @override
  _i4.Future<void> cacheJokes(List<_i2.JokeModel>? jokes) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheJokes,
          [jokes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> incrementViewCount(int? jokeId) => (super.noSuchMethod(
        Invocation.method(
          #incrementViewCount,
          [jokeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetViewCounters() => (super.noSuchMethod(
        Invocation.method(
          #resetViewCounters,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.JokeModel> createJoke({
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJoke,
          [],
          {
            #question: question,
            #answer: answer,
          },
        ),
        returnValue: _i4.Future<_i2.JokeModel>.value(_FakeJokeModel_0(
          this,
          Invocation.method(
            #createJoke,
            [],
            {
              #question: question,
              #answer: answer,
            },
          ),
        )),
      ) as _i4.Future<_i2.JokeModel>);

  @override
  _i4.Future<_i2.JokeModel> updateJoke({
    required int? id,
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJoke,
          [],
          {
            #id: id,
            #question: question,
            #answer: answer,
          },
        ),
        returnValue: _i4.Future<_i2.JokeModel>.value(_FakeJokeModel_0(
          this,
          Invocation.method(
            #updateJoke,
            [],
            {
              #id: id,
              #question: question,
              #answer: answer,
            },
          ),
        )),
      ) as _i4.Future<_i2.JokeModel>);

  @override
  _i4.Future<void> deleteJoke(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJoke,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [JokeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJokeRemoteDataSource extends _i1.Mock
    implements _i5.JokeRemoteDataSource {
  MockJokeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.JokeModel>> getJokes() => (super.noSuchMethod(
        Invocation.method(
          #getJokes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.JokeModel>>.value(<_i2.JokeModel>[]),
      ) as _i4.Future<List<_i2.JokeModel>>);

  @override
  _i4.Future<_i2.JokeModel> createJoke({
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJoke,
          [],
          {
            #question: question,
            #answer: answer,
          },
        ),
        returnValue: _i4.Future<_i2.JokeModel>.value(_FakeJokeModel_0(
          this,
          Invocation.method(
            #createJoke,
            [],
            {
              #question: question,
              #answer: answer,
            },
          ),
        )),
      ) as _i4.Future<_i2.JokeModel>);

  @override
  _i4.Future<_i2.JokeModel> updateJoke({
    required int? id,
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJoke,
          [],
          {
            #id: id,
            #question: question,
            #answer: answer,
          },
        ),
        returnValue: _i4.Future<_i2.JokeModel>.value(_FakeJokeModel_0(
          this,
          Invocation.method(
            #updateJoke,
            [],
            {
              #id: id,
              #question: question,
              #answer: answer,
            },
          ),
        )),
      ) as _i4.Future<_i2.JokeModel>);

  @override
  _i4.Future<void> deleteJoke(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJoke,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncViewCounts(List<_i2.JokeModel>? localJokes) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncViewCounts,
          [localJokes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> incrementLike(int? jokeId) => (super.noSuchMethod(
        Invocation.method(
          #incrementLike,
          [jokeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> incrementDislike(int? jokeId) => (super.noSuchMethod(
        Invocation.method(
          #incrementDislike,
          [jokeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
